#!/usr/bin/env python3
"""
omr-wiki Implementation
Wiki generation from synthesis
"""

import json
from pathlib import Path
from typing import Dict, List
from datetime import datetime

def generate_wiki(workspace_root: Path) -> Dict:
    """
    Generate wiki from synthesis content

    Args:
        workspace_root: Project workspace

    Returns:
        Dict with wiki output
    """
    docs_dir = workspace_root / 'docs'
    wiki_dir = workspace_root / 'wiki'

    # Check for synthesis content
    synthesis_modes = ['survey', 'report', 'manuscript', 'brief']
    synthesis_dir = None

    for mode in synthesis_modes:
        potential_dir = docs_dir / mode
        if potential_dir.exists() and any(potential_dir.glob('*.md')):
            synthesis_dir = potential_dir
            break

    if not synthesis_dir:
        # Check for judgment summary
        judgment_path = docs_dir / 'judgment-summary.md'
        if judgment_path.exists():
            # Generate wiki from judgment
            wiki_dir.mkdir(parents=True, exist_ok=True)
            wiki_content = generate_from_judgment(judgment_path.read_text())
            wiki_path = wiki_dir / 'main.md'
            wiki_path.write_text(wiki_content)

            return {
                'status': 'success',
                'wiki_path': str(wiki_path),
                'source': 'judgment-summary'
            }

        return {
            'status': 'failed',
            'error': 'No synthesis content found'
        }

    # Generate wiki from synthesis
    wiki_dir.mkdir(parents=True, exist_ok=True)

    # Convert synthesis chapters to wiki pages
    wiki_pages = []
    for chapter_file in synthesis_dir.glob('*.md'):
        if chapter_file.name == 'index.md':
            continue

        # Read chapter
        chapter_content = chapter_file.read_text()

        # Convert to wiki format
        wiki_page = convert_to_wiki(chapter_content, chapter_file.stem)

        # Write wiki page
        wiki_page_path = wiki_dir / f"{chapter_file.stem}.md"
        wiki_page_path.write_text(wiki_page)

        wiki_pages.append({
            'title': chapter_file.stem,
            'path': str(wiki_page_path)
        })

    # Generate wiki index with cross-references
    wiki_index = generate_wiki_index(wiki_pages)
    wiki_index_path = wiki_dir / 'index.md'
    wiki_index_path.write_text(wiki_index)

    return {
        'status': 'success',
        'wiki_dir': str(wiki_dir),
        'pages': len(wiki_pages),
        'index': str(wiki_index_path)
    }

def convert_to_wiki(chapter_content: str, page_name: str) -> str:
    """
    Convert synthesis chapter to wiki format

    Args:
        chapter_content: Chapter markdown
        page_name: Page name

    Returns:
        Wiki-formatted markdown
    """
    # Add wiki header
    wiki_header = f"""---
title: {page_name}
generated: {datetime.now().isoformat()}
---

"""

    # Add cross-reference section
    wiki_footer = f"""

## Related Pages

- [[index]] - Wiki index
- See synthesis source for detailed references

---
_Generated by omr-wiki_"""

    return wiki_header + chapter_content + wiki_footer

def generate_from_judgment(judgment_content: str) -> str:
    """
    Generate wiki page from judgment summary

    Args:
        judgment_content: Judgment markdown

    Returns:
        Wiki-formatted page
    """
    return f"""---
title: Research Summary
generated: {datetime.now().isoformat()}
---

# Research Summary

{judgment_content}

## Related Pages

- [[index]] - Wiki index

---
_Generated by omr-wiki_"""

def generate_wiki_index(wiki_pages: List[Dict]) -> str:
    """
    Generate wiki index with cross-references

    Args:
        wiki_pages: List of wiki page dicts

    Returns:
        Index markdown
    """
    lines = [
        "---",
        "title: Wiki Index",
        f"generated: {datetime.now().isoformat()}",
        "---",
        "",
        "# Wiki Index",
        "",
        f"**Generated**: {datetime.now().isoformat()}",
        "",
        "---",
        "",
        "## Pages",
        ""
    ]

    for page in wiki_pages:
        title = page['title'].replace('-', ' ').title()
        lines.append(f"- [[{page['title']}]] - {title}")

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("_Generated by omr-wiki_")

    return "\n".join(lines)

def main():
    """CLI entry point"""
    import sys

    if len(sys.argv) < 2:
        print("Usage: generate_wiki.py <workspace>")
        sys.exit(1)

    workspace = Path(sys.argv[1])

    print("Generating wiki...")
    result = generate_wiki(workspace)

    if result['status'] == 'success':
        print(f"✓ Wiki generated")
        print(f"  Directory: {result['wiki_dir'] or result['wiki_path']}")
        print(f"  Pages: {result['pages']}")
        print(f"  Index: {result['index']}")

    else:
        print(f"✗ Error: {result['error']}")

if __name__ == "__main__":
    main()