#!/usr/bin/env python3
"""
omr-research-plan Implementation (Merged Skill)
Judges evidence + plans research approach (merged from brainstorming session 1)
"""

import json
from pathlib import Path
from typing import Dict
from datetime import datetime

def plan_research(workspace_root: Path) -> Dict:
    """
    Judge evidence and plan research approach (merged skill)

    Args:
        workspace_root: Project workspace root

    Returns:
        Dict with judgment summary and research plan
    """
    docs_dir = workspace_root / 'docs'

    # Read evidence map
    evidence_map_path = docs_dir / 'evidence-map.md'

    if not evidence_map_path.exists():
        return {
            'status': 'failed',
            'error': 'evidence-map.md not found. Run omr-evidence first.'
        }

    evidence_map = evidence_map_path.read_text()

    # Judge evidence (synthesize main conclusion)
    judgment = synthesize_judgment(evidence_map)

    # Plan research approach
    plan = create_research_plan(evidence_map, judgment)

    # Write outputs
    judgment_path = docs_dir / 'judgment-summary.md'
    judgment_path.write_text(judgment['markdown'])

    plan_path = docs_dir / 'research-plan.md'
    plan_path.write_text(plan['markdown'])

    # Gate A: Evidence sufficient for planning?
    gate_passed = check_gate_a(evidence_map)

    if not gate_passed['passed']:
        return {
            'status': 'gate_failed',
            'gate': 'A',
            'message': gate_passed['message'],
            'judgment_path': str(judgment_path),
            'plan_path': str(plan_path)
        }

    # Update skill tree
    update_tree_state(workspace_root)

    return {
        'status': 'success',
        'gate_passed': gate_passed['passed'],
        'judgment_path': str(judgment_path),
        'plan_path': str(plan_path),
        'main_conclusion': judgment['conclusion'],
        'confidence': judgment['confidence'],
        'priorities': len(plan['priorities'])
    }

def synthesize_judgment(evidence_map: str) -> Dict:
    """
    Synthesize judgment from evidence map

    Simplified: Placeholder - real would use LLM

    Args:
        evidence_map: Evidence map markdown content

    Returns:
        Dict with conclusion, confidence, markdown
    """
    # Parse evidence map (simplified)
    # Extract claims count, gaps count

    claims_count = evidence_map.count('**C-')

    gaps_count = evidence_map.count('**G-')

    # Placeholder judgment synthesis
    conclusion = "Collected evidence provides foundation for research planning"

    confidence = "medium" if claims_count < 5 else "high"

    markdown = f"""# Judgment Summary

**Generated**: {datetime.now().isoformat()}

---

## Main Conclusion

{conclusion}

**Confidence**: {confidence}

---

## Evidence Quality

- **Claims Analyzed**: {claims_count}
- **Gaps Identified**: {gaps_count}
- **Coverage**: {claims_count} sources reviewed

---

## Judgment

Based on {claims_count} extracted claims and {gaps_count} identified gaps, the evidence foundation is {'sufficient' if claims_count >= 3 else 'insufficient'} for research planning.

{'Evidence coverage adequate for proceeding with research planning.' if claims_count >= 3 else 'Additional materials may strengthen evidence foundation.'}

---

_Generated by omr-research-plan (merged skill: judgment + planning)_"""

    return {
        'conclusion': conclusion,
        'confidence': confidence,
        'markdown': markdown
    }

def create_research_plan(evidence_map: str, judgment: Dict) -> Dict:
    """
    Create research plan from evidence and judgment

    Args:
        evidence_map: Evidence map content
        judgment: Judgment dict

    Returns:
        Dict with priorities, timeline, markdown
    """
    # Placeholder priorities (simplified)
    priorities = [
        {
            'priority': 1,
            'task': 'Review collected materials comprehensively',
            'estimated_time': '1-2 days'
        },
        {
            'priority': 2,
            'task': 'Address identified research gaps',
            'estimated_time': '2-3 days'
        },
        {
            'priority': 3,
            'task': 'Synthesize findings into architectural decisions',
            'estimated_time': '1 day'
        }
    ]

    timeline = "3-5 days estimated"

    markdown = f"""# Research Plan

**Generated**: {datetime.now().isoformat()}

**Judgment**: {judgment['conclusion']} (Confidence: {judgment['confidence']})

---

## Research Priorities

"""

    for priority in priorities:
        markdown += f"**Priority {priority['priority']}**: {priority['task']}\n"
        markdown += f"- Estimated time: {priority['estimated_time']}\n\n"

    markdown += "---\n\n"
    markdown += "## Timeline\n\n"
    markdown += f"**Total Estimated**: {timeline}\n\n"

    markdown += "---\n\n"
    markdown += "## Success Criteria\n\n"
    markdown += "- [ ] Evidence comprehensively reviewed\n"
    markdown += "- [ ] Research gaps addressed\n"
    markdown += "- [ ] Architectural decisions documented\n"
    markdown += "- [ ] Validation completed\n\n"

    markdown += "\n_Generated by omr-research-plan (merged skill)_"

    return {
        'priorities': priorities,
        'timeline': timeline,
        'markdown': markdown
    }

def check_gate_a(evidence_map: str) -> Dict:
    """
    Gate A: Evidence sufficient for planning?

    Checks:
    - Evidence coverage adequate
    - Research question clear
    - Scope defined

    Args:
        evidence_map: Evidence map content

    Returns:
        Dict with passed, message
    """
    # Simplified gate checks
    claims_count = evidence_map.count('**C-')

    # Check coverage
    coverage_adequate = claims_count >= 3

    # Check research question present
    question_present = 'Question ID' in evidence_map

    # Check scope defined
    scope_defined = 'Scope' in evidence_map

    passed = coverage_adequate and question_present and scope_defined

    if passed:
        message = "Gate A passed: Evidence sufficient for research planning"
    else:
        missing = []
        if not coverage_adequate:
            missing.append("Evidence coverage insufficient")
        if not question_present:
            missing.append("Research question unclear")
        if not scope_defined:
            missing.append("Scope not defined")

        message = f"Gate A failed: {', '.join(missing)}"

    return {
        'passed': passed,
        'message': message,
        'checks': {
            'coverage_adequate': coverage_adequate,
            'question_present': question_present,
            'scope_defined': scope_defined
        }
    }

def update_tree_state(workspace_root: Path):
    """
    Update skill tree to unlock downstream skills

    Args:
        workspace_root: Project workspace
    """
    tree_state_path = workspace_root / 'skills' / 'tree-state.json'

    if not tree_state_path.exists():
        return

    state = json.loads(tree_state_path.read_text())

    # Mark omr-research-plan as completed
    if 'omr-research-plan' in state['ready']:
        state['ready'].remove('omr-research-plan')

    state['completed'].append('omr-research-plan')

    # Unlock omr-decision
    if 'omr-decision' in state['locked']:
        state['locked'].remove('omr-decision')
        state['ready'].append('omr-decision')

    tree_state_path.write_text(json.dumps(state, indent=2))

def main():
    """CLI entry point"""
    import sys

    if len(sys.argv) < 2:
        print("Usage: plan_research.py <workspace>")
        print("Example: plan_research.py /tmp/test-project")
        sys.exit(1)

    workspace = Path(sys.argv[1])

    print("Judging evidence and planning research approach...")
    result = plan_research(workspace)

    if result['status'] == 'success':
        print(f"✓ Research planning complete")
        print(f"  Judgment: {result['judgment_path']}")
        print(f"  Plan: {result['plan_path']}")
        print(f"  Main conclusion: {result['main_conclusion']}")
        print(f"  Confidence: {result['confidence']}")
        print(f"  Priorities: {result['priorities']}")

        if result['gate_passed']:
            print(f"\n⚠️  GATE A: Passed")
            print(f"  Evidence sufficient for planning")

        print(f"\n📊 Skill tree updated")
        print(f"  - omr-decision [READY]")

    elif result['status'] == 'gate_failed':
        print(f"⚠️  GATE A FAILED")
        print(f"  {result['message']}")
        print(f"\n  Review: {result['judgment_path']}")
        print(f"  Plan draft: {result['plan_path']}")

    else:
        print(f"✗ Error: {result['error']}")

if __name__ == "__main__":
    main()