#!/usr/bin/env python3
"""
omr-idea-note Implementation
Captures speculative insights separate from objective findings
"""

import json
import sys
from pathlib import Path
from datetime import datetime
from typing import Dict

def capture_idea(workspace_root: Path, idea_text: str) -> Dict:
    """
    Capture research idea/insight

    Args:
        workspace_root: Project workspace
        idea_text: Idea text from user

    Returns:
        Dict with idea note path
    """
    docs_dir = workspace_root / 'docs'
    ideas_dir = docs_dir / 'ideas'
    ideas_dir.mkdir(parents=True, exist_ok=True)

    # Generate idea ID
    timestamp = datetime.now().strftime('%Y%m%d-%H%M%S')
    idea_id = f"idea-{timestamp}"

    # Classify idea type
    idea_type = classify_idea_type(idea_text)

    # Generate idea note
    idea_note = generate_idea_note(
        idea_id=idea_id,
        idea_text=idea_text,
        idea_type=idea_type,
        workspace_root=workspace_root
    )

    # Write idea note
    idea_path = ideas_dir / f"{idea_id}.md"
    idea_path.write_text(idea_note['markdown'])

    # Update artifacts index
    update_artifacts_index(workspace_root, idea_path, idea_id)

    return {
        'status': 'success',
        'idea_path': str(idea_path),
        'idea_id': idea_id,
        'idea_type': idea_type
    }

def classify_idea_type(idea_text: str) -> str:
    """Classify idea as hypothesis/observation/question/speculation"""
    idea_lower = idea_text.lower()

    # Check for question
    if '?' in idea_text:
        return 'question'

    # Check for hypothesis (testable speculation)
    if any(kw in idea_lower for kw in ['test', 'experiment', 'validate', 'evaluate']):
        return 'hypothesis'

    # Check for speculation
    if any(kw in idea_lower for kw in ['could', 'might', 'would', 'should', 'maybe', 'perhaps']):
        return 'speculation'

    # Default to observation
    return 'observation'

def generate_idea_note(idea_id: str, idea_text: str, idea_type: str, workspace_root: Path) -> Dict:
    """Generate idea note markdown"""

    # Find related artifacts
    related = find_related_artifacts(idea_text, workspace_root)

    # Generate next steps based on type
    next_steps = generate_next_steps(idea_type)

    markdown = f"""# Idea: {idea_id}

**Type**: {idea_type}

**Captured**: {datetime.now().isoformat()}

---

## Insight

{idea_text}

---

## Evidence Boundary

**Status**: Speculation - needs validation

**Note**: This is a subjective insight, separate from objective findings in evidence map. This idea has not been proven or suggested by evidence yet.

---

## Related Artifacts

{related}

---

## Next Steps

{next_steps}

---

_Generated by omr-idea-note_
"""

    return {'markdown': markdown}

def find_related_artifacts(idea_text: str, workspace_root: Path) -> str:
    """Find related artifacts for context"""
    docs_dir = workspace_root / 'docs'

    related = []

    # Check for decision references
    decision_files = [
        'architecture-decision.md',
        'docs/plans/decision-*.md'
    ]

    for pattern in decision_files:
        if '*' in pattern:
            # Glob pattern
            for file in docs_dir.glob(pattern):
                related.append(f"- Decision: {file.name}")
        else:
            file_path = docs_dir / pattern
            if file_path.exists():
                related.append(f"- Decision: {file_path.name}")

    # Check for evaluation references
    eval_files = [
        'evaluation-report.md',
        'docs/plans/report-*.md'
    ]

    for pattern in eval_files:
        if '*' in pattern:
            for file in docs_dir.glob(pattern):
                related.append(f"- Evaluation: {file_path.name}")
        else:
            file_path = docs_dir / pattern
            if file_path.exists():
                related.append(f"- Evaluation: {file_path.name}")

    # Check for evidence map
    evidence_map = docs_dir / 'evidence-map.md'
    if evidence_map.exists():
        related.append("- Evidence: evidence-map.md")

    return "\n".join(related) if related else "None (new idea)"

def generate_next_steps(idea_type: str) -> str:
    """Generate next steps based on idea type"""
    if idea_type == 'hypothesis':
        return """- Run `/omr-evaluation` to test hypothesis
- Update evidence map if proven or disproven
- Link to synthesis if confirmed"""
    elif idea_type == 'question':
        return """- Run `/omr-collection` to gather materials addressing this question
- Run `/omr-evidence` to extract evidence
- Run `/omr-synthesis` to document findings"""
    elif idea_type == 'speculation':
        return """- Consider running `/omr-evaluation` to validate speculation
- Discuss with domain experts before investing in experiments
- Link to decision if it influences architecture"""
    else:  # observation
        return """- Run `/omr-evidence` to see if observation aligns with collected evidence
- Run `/omr-synthesis` to include in findings if relevant"""

def update_artifacts_index(workspace_root: Path, idea_path: Path, idea_id: str):
    """Update artifacts index with new idea"""
    docs_dir = workspace_root / 'docs'
    index_dir = docs_dir / 'index'
    index_dir.mkdir(parents=True, exist_ok=True)

    index_path = index_dir / 'artifacts-index.json'

    if index_path.exists():
        index_data = json.loads(index_path.read_text())
    else:
        index_data = {'artifacts': [], 'last_updated': datetime.now().isoformat()}

    # Add idea to index
    artifact_entry = {
        'id': idea_id,
        'type': 'idea',
        'path': str(idea_path.relative_to(workspace_root)),
        'created_at': datetime.now().isoformat(),
        'metadata': {
            'idea_type': classify_idea_type(idea_path.read_text())
        }
    }

    index_data['artifacts'].append(artifact_entry)
    index_data['last_updated'] = datetime.now().isoformat()

    index_path.write_text(json.dumps(index_data, indent=2))

def main():
    """CLI entry point"""
    if len(sys.argv) < 3:
        print("Usage: capture_idea.py <workspace> <idea-text>")
        print("Example: capture_idea.py /path/to/workspace 'Transformer attention could improve memory compression'")
        sys.exit(1)

    workspace = Path(sys.argv[1])
    idea_text = sys.argv[2]

    print(f"Capturing idea...")
    result = capture_idea(workspace, idea_text)

    print(f"✓ Idea captured")
    print(f"  Path: {result['idea_path']}")
    print(f"  Type: {result['idea_type']}")
    print(f"  ID: {result['idea_id']}")

if __name__ == "__main__":
    main()